name: image_tagging_application
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  http: 1.2.1
  image_picker: 1.1.2
  dio: 5.5.0
  path_provider: 2.1.3
  google_generative_ai: 0.4.3
  flutter_dotenv: 5.1.0
  native_exif: 0.6.0
  path: 1.9.0
dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
